# The numpy.random package

In [1]:
import numpy as np

import matplotlib.pyplot as plt

In [2]:
rng = np.random.default_rng()

## What is numpy.random?

### "Simple random data" functions

#### integers

In [3]:
rng.integers(3, size = 20)

array([2, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 0, 0, 2, 1, 1, 0, 2],
      dtype=int64)

#### random

In [9]:
rng.random(size = 20)

array([0.72617183, 0.07099191, 0.10488364, 0.71165325, 0.55924362,
       0.07317471, 0.58406144, 0.45090321, 0.0476465 , 0.8050557 ,
       0.2623049 , 0.70026951, 0.18720878, 0.56524109, 0.35486592,
       0.98048216, 0.45618555, 0.10883659, 0.76169909, 0.89771982])

#### choice

In [25]:
rng.choice(10, 3)

array([2, 9, 8], dtype=int64)

In [26]:
x = ["red", "blue", "green", "black", "yellow"]

In [29]:
rng.choice(x)

'blue'

#### bytes

In [32]:
rng.bytes(5)

b'\xeb\x17\x8ax\xd3'

### "Permutations" functions

#### shuffle

#### permutation

#### permuted

## Distributions

#### binomial

#### normal

#### uniform

#### poisson

#### exponential

## Seeds

## References